### ISSUE TITLE
Registering BioAlignments.jl to BioRegistry?

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/BioAlignments.jl#35]
Hi there!

Today I tried to use BioAlignments.jl along with BioSequences.jl 2.0 and other packages. However, this package is not registered in BioJuliaRegistry and thus it failed to be installed.
I've been away for a while so I'm not pretty sure the current release cycle of BioJulia.
@BenJWard, could you tell me what I should do here?

BTW, I found BioSequences.jl seems to have the same UUID in both General and BioJuliaRegistry. Is it okay?

```
(v1.2) pkg> add BioSequences FASTX
 Resolving package versions...
 Installed BioSymbols ─── v4.0.1
 Installed FASTX ──────── v1.1.0
 Installed BioSequences ─ v2.0.0
  Updating `~/.julia/environments/v1.2/Project.toml`
  [7e6ae17a] + BioSequences v2.0.0
  [c2308a5c] + FASTX v1.1.0
  Updating `~/.julia/environments/v1.2/Manifest.toml`
  [67c07d97] + Automa v0.7.0
  [47718e42] + BioGenerics v0.1.0
  [7e6ae17a] + BioSequences v2.0.0
  [3c28c6f8] + BioSymbols v4.0.1
  [861a8166] + Combinatorics v0.7.0
  [864edb3b] + DataStructures v0.17.0
  [c2308a5c] + FASTX v1.1.0
  [1cb3b9ac] + IndexableBitVectors v1.0.0
  [bac558e1] + OrderedCollections v1.1.0
  [f27b6e38] + Polynomials v0.5.2
  [3bb67fe8] + TranscodingStreams v0.9.5
  [7200193e] + Twiddle v1.1.1
  [2a0f44e3] + Base64
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [de0858da] + Printf
  [9a3f8284] + Random
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [8dfed614] + Test
  [4ec0a83e] + Unicode

(v1.2) pkg> add BioAlignments
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BioAlignments [00701ae9]:
 BioAlignments [00701ae9] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 1.0.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0, 0.3.0, 1.0.0]
 ├─restricted by julia compatibility requirements to versions: 1.0.0 or uninstalled, leaving only versions: 1.0.0
 └─restricted by compatibility requirements with BioSequences [7e6ae17a] to versions: uninstalled — no versions left
   └─BioSequences [7e6ae17a] log:
     ├─possible versions are: [0.5.0, 0.6.0-0.6.3, 0.7.0, 0.8.0-0.8.3, 1.0.0, 1.1.0, 2.0.0] or uninstalled
     └─restricted to versions 2.0.0 by an explicit requirement, leaving only versions 2.0.0
```

**Comment by BenJWard** [comment]
I wouldn't use BioAlignments 1.X with BioSequences 2.X, BioAlignments probably won't work with it since the BioSequences API and type hierarchy has changed from 1.X.

A v2.X is being worked towards by Ciaran, who is doing something similar to what I did with BioSequences: removing the extra parsing machinery to their own complete packages and having BioAlignments just be core alignment types and algorithms. When BioAlignments hits 2.0 I'm happy to put it on the BioJuliaRegistry - which I intend to be the place for the 2.X BioJulia ecosystem - especially the new graph-based framework. Older 1.X era stuff can stay on General.

**Comment by bicycle1885** [comment]
Thank you for your clarification. If there is anything I can help, please feel free to ask me (cc @CiaranOMara).

**Comment by CiaranOMara** [comment]
I believe I have achieved a working separation of the alignment algorithms and the BAM and SAM parsers. @bicycle1885 and @BenJWard it would be grand if you could check the proposed releases:
 - https://github.com/BioJulia/BioAlignments.jl/tree/release/v2.0.0 which includes a relatively straightforward migration to BioGenerics, as well as BioSequences v2.x; and
- https://github.com/BioJulia/XAM.jl/tree/release/v0.1.0, which is only intended to be a minimal working separation where package updates are tackled in its next major release.

**Comment by CiaranOMara** [comment]
The https://github.com/BioJulia/BioAlignments.jl/tree/release/v2.0.0 branch would need to be merged into BioAlignments.jl#master and registered before work on XAM.jl v1.0.0 can progress.

**Comment by CiaranOMara** [comment]
Another dependency for the release of XAM v0.1.0 would be GenonomicFeatures v2.0.0. (see [pre-release/v2.0.0](https://github.com/CiaranOMara/GenomicFeatures.jl/tree/pre-release/v2.0.0) for an example of what that might look like).

**Comment by BenJWard** [comment]
@CiaranOMara v1.0.1 has been released to general. Paving the way for your 2.0 PR.
