### ISSUE TITLE
Incorrect calculation of alignment length in SAM.alignlength()

### ISSUE THREAD

**Issue by herbstk** [BioJulia/BioAlignments.jl#37]
The alignment length is not properly calculated for SAM records using `SAM.alignlength()` also leading to incorrect results with `SAM.rightposition()`.
The problem does not occur in the equivalent BAM accessor functions.

**Comment by CiaranOMara** [comment]
Closed by https://github.com/BioJulia/XAM.jl/commit/5aca5f00111b5e220f637534d487485c308624f7.
