### ISSUE TITLE
Lack of an article to cite BioAlignments.jl

### ISSUE THREAD

**Issue by Hugemiler** [BioJulia/BioAlignments.jl#65]
Hi everyone! I recently built a secondary structure prediction workflow ([check it out!](https://github.com/Hugemiler/TintiNet.jl)) and I'm submitting a manuscript about it. I like to give due credit to every piece of open-source software I used during elaboration and BioAlignments.jl was one of them. I reached out to @kescobo and he suggested I open an issue.

Perhaps the maintainers/authors can work something out, maybe initially a Zenodo release so that at least there's a title, authors and a DOI, and in the future a short communication.

Thanks for your attention!

**Comment by kescobo** [comment]
Closed by #66 and https://github.com/BioJulia/BioAlignments.jl/commit/c49bb0a3cd377ce1652ad6de0718881d05a942d8 - 

```
Kenta Sato, & The BioJulia Organization. (2022). BioJulia/BioAlignments.jl: v2.0.1 zenodo release (v2.0.1). Zenodo. https://doi.org/10.5281/zenodo.6010937
```
