### ISSUE TITLE
How does one access the strand information?

### ISSUE THREAD

**Issue by phaverty** [BioJulia/BioAlignments.jl#9]
When reading each record of a BAM file, where can I find the stand information?

**Comment by phaverty** [comment]
I believe the answer is 

function strand(record::BAM.Record)
    if BAM.flag(record) & 0x10 == 0
        s = STRAND_POS
    else
        s = STRAND_NEG
    end
    s
end

I'd be happy to submit a PR.  Would you want a "strand" function or just a test on the flag to match the other flag tests?

**Comment by BenJWard** [comment]
I think for now a flag test to be consistent with other flag tests, but some convienience methods in the future might be cool to add as well.

**Comment by phaverty** [comment]
OK, I'll put together a PR for the flag test. I have the full function over
at GenomicVectors.jl for now.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by BenJWard** [comment]
Are you happy with this issue now the PR is merged?

**Comment by phaverty** [comment]
Yes, thanks!
